# Generated by Django 6.0.4 on 2026-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParleProduct',
            fields=[
                ('sku_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('mrp', models.IntegerField()),
                ('min_order', models.IntegerField()),
                ('box_amount', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
